from stats_cli.plugins import (
    alias_plugin,
    compare_plugin,
    crawl_status_plugin,
    export_plugin,
    help_plugin,
    history_plugin,
    optimize_plugin,
    player_plugin,
    profile_plugin,
    repair_plugin,
    select_plugin,
    top_plugin,
    top_chart_plugin,
    update_plugin,
    utility_plugin,
)


def install_plugins(
    cls,
    *,
    colorize,
    colors,
    db_safe_operation,
    get_separator,
    get_subseparator,
    get_terminal_width,
    base_dir,
):
    update_plugin.install(cls, colorize=colorize, colors=colors, base_dir=base_dir)
    export_plugin.install(cls, colorize=colorize, colors=colors, db_safe_operation=db_safe_operation)
    optimize_plugin.install(cls, colorize=colorize, colors=colors, base_dir=base_dir)
    crawl_status_plugin.install(cls, colorize=colorize, colors=colors, get_separator=get_separator)
    utility_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        get_separator=get_separator,
        db_safe_operation=db_safe_operation,
    )
    alias_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
    )
    help_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        get_separator=get_separator,
        get_subseparator=get_subseparator,
    )
    select_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        get_separator=get_separator,
    )
    repair_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    top_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
        get_terminal_width=get_terminal_width,
    )
    top_chart_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
    )
    player_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    profile_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
    )
    history_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    compare_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
