from stats_cli.plugins import (
    alias_plugin,
    compare_plugin,
    crawl_status_plugin,
    export_plugin,
    help_plugin,
    history_plugin,
    optimize_plugin,
    player_plugin,
    profile_plugin,
    repair_plugin,
    stb_pie_plugin,
    stb_hot_plugin,
    search_plugin,
    stb_recent_plugin,
    stb_quality_plugin,
    stb_compare_plugin,
    stb_stabled_by_plugin,
    stb_summary_plugin,
    stb_trends_plugin,
    select_plugin,
    stb_stats_plugin,
    top_plugin,
    top_chart_plugin,
    trend_plugin,
    update_plugin,
    utility_plugin,
)


def install_plugins(
    cls,
    *,
    colorize,
    colors,
    db_safe_operation,
    get_separator,
    get_subseparator,
    get_terminal_width,
    base_dir,
):
    update_plugin.install(cls, colorize=colorize, colors=colors, base_dir=base_dir)
    export_plugin.install(cls, colorize=colorize, colors=colors, db_safe_operation=db_safe_operation)
    optimize_plugin.install(cls, colorize=colorize, colors=colors, base_dir=base_dir)
    crawl_status_plugin.install(cls, colorize=colorize, colors=colors, get_separator=get_separator)
    utility_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        get_separator=get_separator,
        db_safe_operation=db_safe_operation,
    )
    alias_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
    )
    help_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        get_separator=get_separator,
        get_subseparator=get_subseparator,
    )
    select_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        get_separator=get_separator,
    )
    repair_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    top_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
        get_terminal_width=get_terminal_width,
    )
    top_chart_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
    )
    trend_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    search_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    stb_stats_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    stb_pie_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
    )
    stb_recent_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    stb_hot_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    stb_summary_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    stb_quality_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    stb_trends_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    stb_compare_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    stb_stabled_by_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    player_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    profile_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
    )
    history_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
    compare_plugin.install(
        cls,
        colorize=colorize,
        colors=colors,
        db_safe_operation=db_safe_operation,
        get_separator=get_separator,
    )
